"""rules_typst examples"""

module(
    name = "rules_typst_examples",
    version = "0.0.0",
)

bazel_dep(name = "rules_typst", version = "0.0.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "bazel_lib", version = "3.2.1")

local_path_override(
    module_name = "rules_typst",
    path = "..",
)

typst_packages = use_extension(
    "@rules_typst//typst:extensions.bzl",
    "typst_packages",
)
typst_packages.package(
    name = "a2c-nums",
    integrity = "sha256-nrBYr7gZfxYldHKz0gZ1o5XjCX301rHIEO3s4exSOhw=",
    version = "0.0.1",
)
typst_packages.package(
    name = "cetz",
    integrity = "sha256-d8+EkBFK4ExuZloR76aR0oSgytuXGXcbVwjBGXKS8j8=",
    version = "0.5.2",
)
typst_packages.package(
    name = "oxifmt",
    integrity = "sha256-fReh/IrQF0DsPLKwPHNgpCJf+TGOVxB2X6mOpv1ZWU8=",
    version = "1.0.0",
)
typst_packages.package(
    name = "zap",
    integrity = "sha256-Lq30CKTE7wdk45okSF5LhNkXuZTbf6UbEI71nwWsApk=",
    version = "0.6.0",
)
use_repo(typst_packages, "typst_packages")
