load("@rules_rust//rust:defs.bzl", "rust_test")
load("@rules_rust//rust:rust_binary.bzl", "rust_binary")

rust_binary(
    name = "process_wrapper",
    srcs = ["process_wrapper.rs"],
    edition = "2021",
    visibility = ["//visibility:public"],
)

rust_test(
    name = "process_wrapper_test",
    srcs = ["process_wrapper.rs"],
    edition = "2021",
)
